name: 发布测试

env:
  TZ: Asia/Shanghai
  ANDROID_VERSION: 'android16'
  KERNEL_VERSION: '6.12'
  SUB_VERSION: '23'
  KERNEL_NAME: 'android16-5-ga8f88ad96df3-ab13929693-4k'
  CCACHE_KEY: ccache-neov5-6.12.23

on:
  workflow_dispatch:
    inputs:
      ksu_type:
        description: 'KernelSU分支(ReSukiSU/SukiSU Ultra/KernelSU Next/KSU(原版)/无内置KSU,默认ReSukiSU)'
        required: true
        type: choice
        default: 'resukisu'
        options:
          - 'resukisu'
          - 'sukisu'
          - 'ksunext'
          - 'ksu'
          - 'none'
      susfs_enable:
        description: '是否开启susfs(用于增强隐藏环境挂载功能; 可能轻微增加耗电，上游更新导致不稳定时或不需要可关闭)'
        required: true
        type: boolean
        default: 'true'
      kpm_enable:
        description: '是否开启kpm(builtin-使用(re)sukisu内置kpm, kpn-使用独立kpm实现(支持任意KSU/面具环境); 不需要可保持默认关闭)'
        required: true
        type: choice
        default: 'false'
        options:
          - 'false'
          - 'builtin'
          - 'kpn'
      lz4_enable:
        description: '是否安装 lz4 1.10.0+zstd 1.5.7 补丁及 LZ4KD 补丁'
        required: true
        type: boolean
        default: 'true'
      lz4kd_enable:
        description: '是否安装 LZ4KD 补丁(若已开启lz4+zstd补丁则可不开启)'
        required: true
        type: boolean
        default: 'false'
      bbr_enable:
        description: '是否启用bbr算法(优化上行数据,对手机日用无太大意义甚至可能负优化;false关闭,true仅加入算法,default设为默认)'
        required: true
        type: choice
        default: 'false'
        options:
          - 'false'
          - 'true'
          - 'default'
      better_net:
        description: '是否开启网络功能拓展配置(用于为ipset及需要iptables等高级网络功能内核支持的程序提供支持)'
        required: true
        type: boolean
        default: 'false'
      adios_enable:
        description: '是否启用ADIOS IO调度器支持(提升IO读写性能)'
        required: true
        type: boolean
        default: 'true'
      rekernel_enable:
        description: '是否启用Re-Kernel支持(与Freezer/NoActive等软件配合, 提升应用冻结能力)'
        required: true
        type: boolean
        default: 'false'
      baseband_guard:
        description: '是否开启内核级基带保护(阻止一切对非用户分区的写入，有效防止格机)'
        required: true
        type: boolean
        default: 'true'
      kernel_suffix:
        description: '内核后缀(留空默认,开头别加连字符,勿加空格等影响指令运行的保留字符)'
        required: false
        type: string
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      ksuver: ${{ steps.ksu_version.outputs.ksuver }}
      ak3name: ${{ steps.create_zip.outputs.ak3name }}
    steps:
      - name: 添加KernelSU版本号
        id: ksu_version
        run: |
          KSU_VERSION="114514"
          echo "KSUVER=$KSU_VERSION" >> $GITHUB_ENV
          echo "ksuver=$KSU_VERSION" >> $GITHUB_OUTPUT
          #export KSUVER=$KSU_VERSION
          
      - name: 克隆 AnyKernel3 并打包
        id: create_zip
        run: |
          if [[ ${{ github.event.inputs.ksu_type }} == "sukisu" ]]; then
            KSU_TYPENAME="SukiSU"
          elif [[ ${{ github.event.inputs.ksu_type }} == "resukisu" ]]; then
            KSU_TYPENAME="ReSukiSU"
          elif [[ ${{ github.event.inputs.ksu_type }} == "ksunext" ]]; then
            KSU_TYPENAME="KSUNext"
          elif [[ ${{ github.event.inputs.ksu_type }} == "ksu" ]]; then
            KSU_TYPENAME="KSU"
          else
            KSU_TYPENAME="none"
          fi
          #echo "KSU_TYPENAME=$KSU_TYPENAME" >> $GITHUB_ENV
          if [[ -n "${{ github.event.inputs.kernel_suffix }}" ]]; then
            AK3_NAME=AnyKernel3_${KSU_TYPENAME}_${{ env.KSUVER }}_${{ env.KERNEL_VERSION }}_${{ github.event.inputs.kernel_suffix }}.zip
          else
            AK3_NAME=AnyKernel3_${KSU_TYPENAME}_${{ env.KSUVER }}_${{ env.KERNEL_VERSION }}_${{ env.KERNEL_NAME }}.zip
          fi
          truncate -s 30M testfile
          zip -r ./$AK3_NAME ./testfile
          echo "ak3name=$AK3_NAME" >> $GITHUB_OUTPUT

      - name: 上传 ZIP 工件
        uses: actions/upload-artifact@v7
        with:
          path: ${{ github.workspace }}/AnyKernel*.zip
          archive: false

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      actions: read
      
    steps:
      - name: 下载 ZIP 工件
        uses: actions/download-artifact@v8
        with:
          name: ${{ needs.build.outputs.ak3name }}
          path: ./release_zips
          skip-decompress: true

      - name: 设置环境变量
        run: |
          if [[ -n "${{ github.event.inputs.kernel_suffix }}" ]]; then
            FULL_VERSION=${{ env.KERNEL_VERSION }}.${{ env.SUB_VERSION }}-${{ github.event.inputs.kernel_suffix }}
            echo "FULL_VERSION=$FULL_VERSION" >> $GITHUB_ENV
            export FULL_VERSION=$FULL_VERSION
          else
            FULL_VERSION=${{ env.KERNEL_VERSION }}.${{ env.SUB_VERSION }}-${{ env.KERNEL_NAME }}
            echo "FULL_VERSION=$FULL_VERSION" >> $GITHUB_ENV
            export FULL_VERSION=$FULL_VERSION
          fi
          TIME="$(TZ='Asia/Shanghai' date +'%y%m%d%H%M%S')"
          TIME_FORM="$(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M:%S')"
          echo "TIME=$TIME" >> $GITHUB_ENV
          echo "TIME_FORM=$TIME_FORM" >> $GITHUB_ENV
          TAG_HEAD="OPPO-OPlus-Realme-build"
          echo "TAG_HEAD=$TAG_HEAD" >> $GITHUB_ENV
          if [[ ${{ github.event.inputs.ksu_type }} == "sukisu" ]]; then
            KSU_TYPENAME="SukiSU Ultra"
          elif [[ ${{ github.event.inputs.ksu_type }} == "resukisu" ]]; then
            KSU_TYPENAME="ReSukiSU"
          elif [[ ${{ github.event.inputs.ksu_type }} == "ksunext" ]]; then
            KSU_TYPENAME="KernelSU Next"
          elif [[ ${{ github.event.inputs.ksu_type }} == "ksu" ]]; then
            KSU_TYPENAME="KernelSU (Official)"
          else
            KSU_TYPENAME="无内置KSU"
          fi
          echo "KSU_TYPENAME=$KSU_TYPENAME" >> $GITHUB_ENV
         
      - name: 创建发布
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cat << 'EOF' > release_notes.md
          ### 📱 欧加真 ${{ env.KSU_TYPENAME }} sm8850 通用内核 | 构建信息
          - 内核版本号: ${{ env.FULL_VERSION }}
          - 编译时间: ${{ env.TIME_FORM }}
          - 机型：欧加真骁龙8E Gen5通用 ${{ env.KERNEL_VERSION }}.${{ env.SUB_VERSION }} 内核（基于一加15 ${{ env.KERNEL_VERSION }}.${{ env.SUB_VERSION }} 版官方源码）
          - KSU分支：${{ env.KSU_TYPENAME }}
          - susfs支持：${{ github.event.inputs.susfs_enable }}
          - KPM支持 ：${{ github.event.inputs.kpm_enable }}
          - LZ4支持：${{ github.event.inputs.lz4_enable }}
          - LZ4KD支持：${{ github.event.inputs.lz4kd_enable }}
          - 网络功能增强：${{ github.event.inputs.better_net }}
          - BBR/Brutal 等拥塞控制算法支持：${{ github.event.inputs.bbr_enable }}
          - ADIOS IO调度器支持：${{ github.event.inputs.adios_enable }}
          - Re-Kernel支持：${{ github.event.inputs.rekernel_enable }}
          - 内核级基带保护支持：${{ github.event.inputs.baseband_guard }}
          - ReSukiSU管理器下载：[ReSukiSU_CI](https://github.com/cctv18/ReSukiSU_CI/releases)
          - SukiSU Ultra管理器下载：[SukiSU-Ultra](https://github.com/SukiSU-Ultra/SukiSU-Ultra/releases)
          - KernelSU Next管理器下载：[KernelSU-Next](https://github.com/KernelSU-Next/KernelSU-Next/releases)
          - KSU原版管理器下载：[KernelSU](https://github.com/tiann/KernelSU/releases)
          
          ### ⏫️ 更新内容：
          - 更新${{ env.KSU_TYPENAME }}至最新版本（${{ needs.build.outputs.ksuver }}）
          - (预留)
          
          ### 📋 安装方法 | Installation Guide
          1. 若你的手机已经安装了第三方Recovery（如TWRP)，可下载对应机型的AnyKernel刷机包后进入Recovery模式，通过Recovery刷入刷机包后重启设备；
          2. 若你的手机之前已有 root 权限，可在手机上安装[HorizonKernelFlasher](https://github.com/libxzr/HorizonKernelFlasher/releases)，在HorizonKernelFlasher中刷入AnyKernel刷机包并重启；
          3. 若你之前已刷入SukiSU Ultra内核，且SukiSU Ultra管理器已更新至最新版本，可在SukiSU Ultra管理器中直接刷入AnyKernel刷机包并重启；
          4. 刷入无lz4kd补丁版的内核前若刷入过lz4kd补丁版的内核，为避免出错，请先关闭zram模块；
          5. 由于KernelSU上游更新了元模块功能，最新版KSU管理器（包括除KernelSU Next以外的各分支）需要配合元模块(metamodule)才能正常挂载模块。目前的元模块包括[meta overlayfs](https://github.com/KernelSU-Modules-Repo/meta-overlayfs), [mountify](https://github.com/backslashxx/mountify), [meta magicmount](https://github.com/7a72/meta-magic_mount/), [meta magicmount rs](https://github.com/Tools-cx-app/meta-magic_mount/), [hybrid mount](https://github.com/YuzakiKokuban/meta-hybrid_mount)等。若你是第一次使用KSU或刚从旧版KSU管理器升级至新版，请先安装一个元模块，这样其他涉及系统挂载的模块才能正常运行；
          6. KernelPatch Next（即KPN）是一个独立于KSU的KPM实现，可以运行在任意KSU/面具环境中（不适用于Apatch），且不能与(Re)SukiSU内置的kpm功能共同使用，使用前请保证你的内核没有内置的kpm实现/修补。
          
          #### ※※※刷写内核有风险，为防止出现意外导致手机变砖，在刷入内核前请务必用[KernelFlasher](https://github.com/capntrips/KernelFlasher)等软件备份boot等关键启动分区!※※※
          EOF

          gh release create "${{ env.TAG_HEAD }}-${{ env.TIME }}" \
            --repo "${{ github.repository }}" \
            --title "${{ env.TAG_HEAD }}-${{ env.FULL_VERSION }}" \
            --notes-file release_notes.md \
            release_zips/AnyKernel3_*.zip
